AWSTemplateFormatVersion: "2010-09-09"
Description: "Merged IAM Managed Policy — Networking Services (deny first, then allow)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network--networking-services
    Description: "IAM managed policy name for Networking Services"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkingServicesPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 5 - Deny: Networking Services

          ## -------------------------------------------------------------------
          ## Service Quotas: prevent Direct Connect quota increases (ticketed process only)
          ## -------------------------------------------------------------------
          - Sid: DenyServiceQuotasDirectConnectIncrease
            Effect: Deny
            Action:
              - servicequotas:RequestServiceQuotaIncrease  ## block quota increase requests for Direct Connect (must go through ticketed path)
            Resource: "*"
            Condition:
              StringEquals:
                servicequotas:service: directconnect       ## scope only to Direct Connect quotas

          ## -------------------------------------------------------------------
          ## Direct Connect administration blocked
          ## -------------------------------------------------------------------
          - Sid: DenyDirectConnectAdministration
            Effect: Deny
            Action:
              - directconnect:Accept*        ## block acceptance of hosted connections/VIFs/associations
              - directconnect:Allocate*      ## block allocation of new hosted connections or VIFs
              - directconnect:Associate*     ## block associating DXGWs/VIFs outside governance
              - directconnect:Attach*        ## block attaching DX resources (LAGs/gateways/etc.)
              - directconnect:Confirm*       ## block confirmations of DX connections/VIFs
              - directconnect:Create*        ## block creation of DX resources (connections/LAGs/GWs/VIFs)
              - directconnect:Delete*        ## block deletion of DX resources (connectivity risk)
              - directconnect:Detach*        ## block detaching DX resources (LAGs/gateways/etc.)
              - directconnect:Disassociate*  ## block disassociating DXGWs/VIFs once established
              - directconnect:Update*        ## block modifying DX resource configs (BGP, VLAN, MTU, etc.)
              - directconnect:TagResource    ## block tag additions on DX resources
              - directconnect:UntagResource  ## block tag removals on DX resources
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Route53 Domains (registrar) admin off (protect org domain ownership)
          ## -------------------------------------------------------------------
          - Sid: DenyRoute53DomainsRegistrarAdministration
            Effect: Deny
            Action:
              - route53domains:AssociateDelegationSignerToDomain       ## block adding DS records
              - route53domains:DeleteDomain                            ## block destructive domain deletions
              - route53domains:DisableDomainAutoRenew                  ## block disabling auto-renew
              - route53domains:DisassociateDelegationSignerFromDomain  ## block removing DS records
              - route53domains:EnableDomainAutoRenew                   ## block enabling auto-renew (governed centrally)
              - route53domains:RegisterDomain                          ## block new domain registrations
              - route53domains:TransferDomain                          ## block outbound transfers
              - route53domains:TransferDomainToAnotherAwsAccount       ## block pushing domains to other accounts
              - route53domains:UpdateDomainContact                     ## block editing registrant/owner contact details
              - route53domains:UpdateDomainContactPrivacy              ## block flipping WHOIS privacy
              - route53domains:UpdateDomainNameservers                 ## block swapping nameservers
              - route53domains:UpdateTagsForDomain                     ## block domain-level tag changes
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 5 - Allow: Networking Services

          ## -------------------------------------------------------------------
          ## Secrets Manager: read-only (value + metadata)
          ## -------------------------------------------------------------------
          - Sid: SecretsManagerRead
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue        ## read secret value
              - secretsmanager:DescribeSecret        ## read secret metadata
              - secretsmanager:ListSecrets           ## list secrets
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Direct Connect: discovery only (no lifecycle)
          ## -------------------------------------------------------------------
          - Sid: DirectConnectReadOnly
            Effect: Allow
            Action:
              - directconnect:Describe*       ## read DX connections/virtual interfaces
              - directconnect:List*           ## list resources
              - directconnect:ViewConnections ## legacy read view
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Service Quotas: read everything (safe)
          ## -------------------------------------------------------------------
          - Sid: ServiceQuotasRead
            Effect: Allow
            Action:
              - servicequotas:Get*   ## read quota values, defaults, templates, and individual requests
              - servicequotas:List*  ## list services, quotas, change requests, and template entries
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Service Quotas: network-scoped requests + template mgmt (covers VPC endpoints, NAT GWs, RTs, SGs, etc.)
          ## -------------------------------------------------------------------
          - Sid: ServiceQuotasNetworkRequestsFull
            Effect: Allow
            Action:
              - servicequotas:RequestServiceQuotaIncrease                ## file increase requests
              - servicequotas:PutServiceQuotaIncreaseRequestIntoTemplate ## manage quota template entries
              - servicequotas:DeleteServiceQuotaIncreaseRequestFromTemplate
              - servicequotas:TagResource
              - servicequotas:UntagResource
            Resource: "*"
            Condition:
              StringEquals:
                servicequotas:service:
                  - ec2                   ## VPCs, subnets, RTs, NAT, ENIs, SGs, **VPC endpoints**, etc.
                  - vpc                   ## some VPC quotas surface under this code in some regions
                  - elasticloadbalancing  ## ALB/NLB counts, listeners, target groups, rules
                  - route53               ## hosted zones, health checks, traffic policies
                  - route53resolver       ## inbound/outbound endpoints, rules, IPs per endpoint
                  - directconnect         ## connections, LAGs, VIFs
                  - globalaccelerator     ## accelerators, listeners, endpoint groups
                  - network-firewall      ## firewalls, policies, rule groups
                  - vpc-lattice           ## service networks, services, auth policies, targets
                  - networkmanager        ## global networks, sites, TGW/R53 integrations
                  - ram                   ## resource shares, associations, permissions

          ## -------------------------------------------------------------------
          ## Service Quotas: organization-wide quota template toggle (OPTIONAL)
          ## Remove this block if template toggles should be centralized elsewhere.
          ## -------------------------------------------------------------------
          - Sid: ServiceQuotasTemplateToggle
            Effect: Allow
            Action:
              - servicequotas:AssociateServiceQuotaTemplate
              - servicequotas:DisassociateServiceQuotaTemplate
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Core networking admin across services (broad control plane)
          ## -------------------------------------------------------------------
          - Sid: NetworkingAdmin
            Effect: Allow
            Action:
              - ec2:*                   ## all EC2 (VPC/Subnets/NACLs/IGWs/TGW/etc.)
              - elasticloadbalancing:*  ## all ELB/ALB/NLB
              - globalaccelerator:*     ## all GA
              - network-firewall:*      ## all AWS Network Firewall
              - networkmanager:*        ## all Network Manager
              - route53resolver:*       ## all Route 53 Resolver
              - vpc-lattice:*           ## all VPC Lattice
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Route 53 + ARC: full admin (authoritative DNS, domains, ARC)
          ## -------------------------------------------------------------------
          - Sid: Route53AndARCAdmin
            Effect: Allow
            Action:
              - route53:*                          ## all hosted zones/records
              - route53profiles:*                  ## Route 53 Profiles
              - route53-recovery-control-config:*  ## ARC routing controls config
              - route53-recovery-readiness:*       ## ARC readiness checks
              - route53-recovery-cluster:*         ## ARC cluster APIs
              - arc-zonal-shift:*                  ## Zonal shift controls
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Route53 Domains (registrar): read-only visibility
          ## -------------------------------------------------------------------
          - Sid: Route53DomainsReadOnly
            Effect: Allow
            Action:
              - route53domains:ListDomains              ## list registered domains
              - route53domains:GetDomainDetail          ## read domain contacts/DNS/privacy
              - route53domains:ListOperations           ## list registrar ops history
              - route53domains:GetOperationDetail       ## read specific op detail
              - route53domains:ListTagsForDomain        ## read domain tags
              - route53domains:ListPrices               ## read pricing
              - route53domains:CheckDomainAvailability  ## availability checks
              - route53domains:GetDomainSuggestions     ## suggestions
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Edge protection (WAFv2/Shield): read-only
          ## -------------------------------------------------------------------
          - Sid: EdgeProtectionReadOnly
            Effect: Allow
            Action:
              - wafv2:Get*        ## get web ACLs/resources
              - wafv2:List*       ## list web ACLs/resources
              - shield:Describe*  ## read Shield protections/events
              - shield:List*      ## list protections
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Internet Monitor & VPC Network Monitor: admin
          ## -------------------------------------------------------------------
          - Sid: InternetAndNetworkMonitorAdmin
            Effect: Allow
            Action:
              - internetmonitor:*  ## manage Internet Monitor
              - networkmonitor:*   ## manage VPC Network Monitor
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  ManagedPolicyArn:
    Description: "Networking Services managed policy's ARN"
    Value: !Ref NetworkingServicesPolicy
