AWSTemplateFormatVersion: "2010-09-09"
Description: "Managed policy for Network Administrator (operations-focused, read-mostly elsewhere)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-administrator-policy
    Description: "AWS IAM managed policy (role naming conventions live on the role)"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkAdministratorManagedPolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Grants network administrators operational control of network services and safe pipeline execution"

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

# ---------------------------------------------------------------------------- #

          ## -------------------------------------------------------------------
          ## ACM: safe ops (no import/delete/options/account-level changes)
          ## -------------------------------------------------------------------
          - Sid: CertificateManagerOpsSafe
            Effect: Allow
            Action:
              - acm:RequestCertificate          ## issue ACM-managed certs (DNS/email validation)
              - acm:DescribeCertificate         ## read cert status/validation/state
              - acm:GetCertificate              ## fetch cert/public chain (no private key)
              - acm:ListCertificates            ## enumerate certs
              - acm:ListTagsForCertificate      ## read tags
              - acm:AddTagsToCertificate        ## add tags
              - acm:RemoveTagsFromCertificate   ## remove tags
              - acm:RenewCertificate            ## trigger managed renewals
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodeArtifact: read-only (no publish/admin)
          ## Purpose: allow consumption of artifacts/packages from approved repos.
          ## No domain/repo admin, no publishing, no upstream/format changes.
          ## -------------------------------------------------------------------
          - Sid: CodeArtifactReadOnly
            Effect: Allow
            Action:
              - codeartifact:Get*            ## read package/version/asset metadata
              - codeartifact:List*           ## enumerate domains/repos/packages
              - codeartifact:ReadFromRepository  ## download package assets
            Resource: "*"                    ## wide by default; can be narrowed to repos

          ## -------------------------------------------------------------------
          ## ECR: read-only/pull (no push/admin)
          ## Purpose: enable docker login and image pulls for CI/diagnostics.
          ## No PutImage, no repo policy/admin, no deletes.
          ## -------------------------------------------------------------------
          - Sid: EcrReadOnlyPull
            Effect: Allow
            Action:
              - ecr:BatchGetImage           ## retrieve image manifests/layers
              - ecr:Describe*               ## describe repos/images/lifecycle policies
              - ecr:GetAuthorizationToken   ## token for 'docker login' (account-scoped)
              - ecr:List*                   ## list repositories/images
            Resource: "*"                   ## GetAuthorizationToken requires "*"

          ## -------------------------------------------------------------------
          ## ECS: read-only (no service/cluster lifecycle)
          ## Purpose: visibility for clusters/services/tasks/events without mutation.
          ## No Create*/Update*/Delete*, no RunTask/Start/Stop.
          ## -------------------------------------------------------------------
          - Sid: EcsReadOnly
            Effect: Allow
            Action:
              - ecs:Describe*               ## describe clusters/services/tasks/container-instances
              - ecs:List*                   ## list clusters/services/tasks/task-definitions
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EKS: read-only (no cluster/nodegroup lifecycle)
          ## Purpose: read cluster/nodegroup/addon state and configs for auditing.
          ## No Create*/Update*/Delete*. Note: does NOT grant Kubernetes RBAC inside clusters.
          ## -------------------------------------------------------------------
          - Sid: EksReadOnly
            Effect: Allow
            Action:
              - eks:Describe*               ## describe clusters/nodegroups/fargate-profiles/addons
              - eks:List*                   ## list clusters/nodegroups/addons
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Service Discovery & Service Catalog: read-only
          ## -------------------------------------------------------------------
          - Sid: ServiceDiscoveryReadOnlyAndCatalogProvisioning
            Effect: Allow
            Action:
              - servicecatalog:Describe*        ## describe resources
              - servicecatalog:Get*             ## read products/portfolios
              - servicecatalog:List*            ## list products/portfolios
              - servicecatalog:SearchProducts*  ## search catalog
              - servicediscovery:Get*           ## read Cloud Map services/namespaces
              - servicediscovery:List*          ## list services/instances
            Resource: "*"

# ---------------------------------------------------------------------------- #

Outputs:

  ## -------------------------------------------------------------------
  ## Resolved ARN of the administrator's managed policy.
  ## -------------------------------------------------------------------
  ManagedPolicyArn:
    Description: "ARN of the NetworkAdministrator managed policy"
    Value: !Ref NetworkAdministratorManagedPolicy
