AWSTemplateFormatVersion: "2010-09-09"
Description: "Managed policy for Network Administrator (operations-focused, read-mostly elsewhere)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network--administrator--policy
    Description: "AWS IAM managed policy (role naming conventions live on the role)"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkAdministratorManagedPolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Grants network administrators operational control of network services and safe pipeline execution"

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

# ---------------------------------------------------------------------------- #

          ## -------------------------------------------------------------------
          ## ACM: safe ops (no import/delete/options/account-level changes)
          ## -------------------------------------------------------------------
          - Sid: CertificateManagerOpsSafe
            Effect: Allow
            Action:
              - acm:RequestCertificate          ## issue ACM-managed certs (DNS/email validation)
              - acm:DescribeCertificate         ## read cert status/validation/state
              - acm:GetCertificate              ## fetch cert/public chain (no private key)
              - acm:ListCertificates            ## enumerate certs
              - acm:ListTagsForCertificate      ## read tags
              - acm:AddTagsToCertificate        ## add tags
              - acm:RemoveTagsFromCertificate   ## remove tags
              - acm:RenewCertificate            ## trigger managed renewals
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodeArtifact — read-only
          ## -------------------------------------------------------------------
          - Sid: CodeArtifactReadOnly
            Effect: Allow
            Action:
              - codeartifact:Get*                   ## read package/version/asset metadata
              - codeartifact:List*                  ## enumerate domains/repos/packages
              - codeartifact:ReadFromRepository     ## download package assets
              - codeartifact:GetAuthorizationToken  ## needed for 'aws codeartifact login' / npm/pip
            Resource: "*"

          ## -------------------------------------------------------------------
          ## ECR — read-only/pull
          ## -------------------------------------------------------------------
          - Sid: EcrReadOnlyPull
            Effect: Allow
            Action:
              - ecr:BatchGetImage                ## retrieve image manifests
              - ecr:BatchCheckLayerAvailability  ## check layer presence
              - ecr:GetDownloadUrlForLayer       ## download image layers
              - ecr:Describe*                    ## describe repos/images/lifecycle policies
              - ecr:GetAuthorizationToken        ## token for 'docker login'
              - ecr:List*                        ## list repositories/images
            Resource: "*"

          ## -------------------------------------------------------------------
          ## ECS — read-only
          ## -------------------------------------------------------------------
          - Sid: EcsReadOnly
            Effect: Allow
            Action:
              - ecs:Describe*  ## describe clusters/services/tasks/container-instances
              - ecs:List*      ## list clusters/services/tasks/task-definitions
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EKS — read-only
          ## -------------------------------------------------------------------
          - Sid: EksReadOnly
            Effect: Allow
            Action:
              - eks:Describe*  ## describe clusters/nodegroups/fargate-profiles/addons
              - eks:List*      ## list clusters/nodegroups/addons
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Service Discovery & Service Catalog: read-only
          ## -------------------------------------------------------------------
          - Sid: ServiceDiscoveryReadOnlyAndCatalogProvisioning
            Effect: Allow
            Action:
              - servicecatalog:Describe*        ## describe resources
              - servicecatalog:Get*             ## read products/portfolios
              - servicecatalog:List*            ## list products/portfolios
              - servicecatalog:SearchProducts*  ## search catalog
              - servicediscovery:Get*           ## read Cloud Map services/namespaces
              - servicediscovery:List*          ## list services/instances
            Resource: "*"

# ---------------------------------------------------------------------------- #

Outputs:

  ## -------------------------------------------------------------------
  ## Resolved ARN of the administrator's managed policy.
  ## -------------------------------------------------------------------
  ManagedPolicyArn:
    Description: "ARN of the NetworkAdministrator managed policy"
    Value: !Ref NetworkAdministratorManagedPolicy
