AWSTemplateFormatVersion: "2010-09-09"
Description: "Common Deny Policy — Development: Source & Orchestration (CodeCommit, CodePipeline)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-deny--workflow-orchestration
    Description: "IAM managed policy name for Development Source & Orchestration deny guardrails"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkDenyOrchestrationPolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Deny guardrails for Development Source & Orchestration (CodeCommit, CodePipeline)"

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 7 - Development — Source & Orchestration

          ## -------------------------------------------------------------------
          ## CodeCommit: prevent repo lifecycle admin; allow normal Git ops
          ## -------------------------------------------------------------------
          - Sid: DenyCodeCommitRepoLifecycleAdmin
            Effect: Deny
            Action:
              - codecommit:CreateRepository             ## block creating repos (must be via IaC/pipeline)
              - codecommit:DeleteRepository             ## block deleting repos (protect history)
              - codecommit:UpdateRepositoryName         ## block renaming repos (breaks remotes/automation)
              - codecommit:UpdateRepositoryDescription  ## block unmanaged description changes
              - codecommit:PutRepositoryTriggers        ## block adding/modifying triggers (exfil paths)
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodePipeline: prevent pipeline lifecycle/admin (definition edits via CFN only)
          ## -------------------------------------------------------------------
          - Sid: DenyCodePipelineLifecycleAdmin
            Effect: Deny
            Action:
              - codepipeline:CreatePipeline  ## block creating pipelines outside IaC
              - codepipeline:UpdatePipeline  ## block editing pipeline definitions manually
              - codepipeline:DeletePipeline  ## block deleting pipelines outside change control
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodePipeline: prevent stage transition toggles
          ## -------------------------------------------------------------------
          - Sid: DenyCodePipelineStageTransitionToggle
            Effect: Deny
            Action:
              - codepipeline:DisableStageTransition  ## block pausing stage transitions
              - codepipeline:EnableStageTransition   ## block resuming transitions outside governance
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodePipeline: prevent webhook administration
          ## -------------------------------------------------------------------
          - Sid: DenyCodePipelineWebhookAdmin
            Effect: Deny
            Action:
              - codepipeline:PutWebhook     ## block creating/updating webhooks
              - codepipeline:DeleteWebhook  ## block deleting governed webhooks
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodePipeline: prevent custom action/job worker APIs
          ## -------------------------------------------------------------------
          - Sid: DenyCodePipelineCustomActionJobs
            Effect: Deny
            Action:
              - codepipeline:CreateCustomActionType         ## block defining custom action types
              - codepipeline:DeleteCustomActionType         ## block deleting custom action types
              - codepipeline:PollForJobs                    ## block human principals polling for jobs
              - codepipeline:AcknowledgeJob                 ## block manual job acknowledgements
              - codepipeline:PutJobSuccessResult            ## block faking job success
              - codepipeline:PutJobFailureResult            ## block forcing job failure
              - codepipeline:AcknowledgeThirdPartyJob       ## block acknowledging 3rd-party jobs
              - codepipeline:GetThirdPartyJobDetails        ## block fetching details of 3rd-party jobs
              - codepipeline:PutThirdPartyJobSuccessResult  ## block faking 3rd-party job success
              - codepipeline:PutThirdPartyJobFailureResult  ## block forcing 3rd-party job failure
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  NetworkDenyOrchestrationPolicyArn:
    Description: "ARN of the Development Source & Orchestration deny IAM managed policy"
    Value: !Ref NetworkDenyOrchestrationPolicy
