AWSTemplateFormatVersion: "2010-09-09"
Description: "Custom Network Administrator's role template that attaches the companion Permissions Boundary and Managed Policies"

Parameters:

  ## AWS account that OWNS the managed policy, boundary, and SAML provider.
  AccountNumber:
    Type: String
    Description: "AWS account ID that owns the IAM resources (policies, SAML provider)"

  ## Policy path prefix used for BOTH: the managed policy and the permissions boundary.
  ## Set to "/" to use the root path.
  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

  ## First token in the role name. Example: "domain", "team", or "org".
  PrefixProfileName:
    Type: String
    Description: "Arbitrary prefix (e.g.: team/domain/org)"

  ## Environment token in the role name (e.g., dev, test, prod).
  EnvironmentName:
    Type: String
    Description: "Environment identifier (e.g: proto, dev, test, uat, prod)"

  ## Base name token in the role name (e.g., network-administrator).
  CustomRoleName:
    Type: String
    Description: "Custom role name (e.g.: network-administrator)"

  ## NAME (not ARN) of the pre-existing managed policy to ATTACH to the role.
  ManagedPolicyName:
    Type: String
    Description: "Name of the required managed policy to be attached (no env suffix here)"

  ## NAME (not ARN) of the permissions boundary managed policy to ENFORCE on the role.
  PermissionsBoundaryPolicyName:
    Type: String
    Description: "Name of the required managed permissions boundary policy to be attached"

  ## SAML provider NAME in this account (the account number is parameterized separately).
  SamlProviderName:
    Type: String
    Description: "SAML provider name used in the federated trust (account is parameterized)"

  ## Optional IAM Role path (for console/AWS IAM path grouping). Keep "/" to avoid nesting.
  CustomRolePath:
    Type: String
    Default: "/role/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "Custom IAM Role's path"

  ## STS session TTL for the role. IAM supports 3600–43200; we cap at 21600 (6h).
  MaxSessionDuration:
    Type: Number
    Default: 3600
    MinValue: 900
    MaxValue: 21600
    Description: "Session duration between 1 - 6 hours (in seconds)"

## When CustomPolicyPath == "/", use "/" directly; otherwise use the provided path.
Conditions:
  PathIsRoot: !Equals [ !Ref CustomPolicyPath, "/" ]

Resources:

  ## ---------------------------------------------------------------------------
  ## IAM Role: name = "<PrefixProfileName>-<EnvironmentName>-<CustomRoleName>-role"
  ## - Trusts SAML provider for AssumeRoleWithSAML (audience locked to AWS sign-in).
  ## - Attaches REQUIRED managed policy.
  ## - Enforces REQUIRED permissions boundary.
  ## ---------------------------------------------------------------------------

  NetworkAdministratorRole:

    Type: AWS::IAM::Role
    Properties:

      RoleName: !Sub "${PrefixProfileName}-${EnvironmentName}-${CustomRoleName}-role"
      Description: "NetworkAdministrator role for prototyping network and infrastructure solutions"
      Path: !Ref CustomRolePath
      MaxSessionDuration: !Ref MaxSessionDuration

      ## -----------------------------------------------------------------------
      ## Trust policy (who can assume?)
      ## -----------------------------------------------------------------------

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:

          # SAML federation (AWS sign-in audience only)
          - Effect: Allow

            Principal:
              Federated: !Sub "arn:aws:iam::${AccountNumber}:saml-provider/${SamlProviderName}"

            Action: "sts:AssumeRoleWithSAML"
            Condition:
              StringEquals:
                SAML:aud: "https://signin.aws.amazon.com/saml"

          # Require session tag mfa=true (via TagSession)
          - Effect: Allow

            Principal:
              Federated: !Sub "arn:aws:iam::${AccountNumber}:saml-provider/${SamlProviderName}"

            Action: "sts:TagSession"
            Condition:

              StringEquals:
                aws:RequestTag/mfa: "true"

              ForAllValues:StringEquals:
                aws:TagKeys: [ mfa ]

      ## Attach the REQUIRED managed policy (name + path resolved into an ARN).
      ManagedPolicyArns:
        # Overlay (unique to this profile)
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}${ManagedPolicyName}"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

        # Common merged segment policies
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--infrastructure"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--utilities-support"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--observability-telemetry"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--systems-management"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--networking-services"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--security-compliance"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--workflow-orchestration"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }
        - !Sub
          - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--workflow-deployment"
          - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

      ## Enforce the REQUIRED permissions boundary (name + path resolved into an ARN).
      PermissionsBoundary: !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}${PermissionsBoundaryPolicyName}"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

## ------------------------------------------------------------------------------
## Outputs — IAM Role
## ------------------------------------------------------------------------------
## Exposes the role identifiers and expected ARNs:
##   - RoleName: CFN Ref -> returns the IAM role NAME (not ARN).
##   - RoleArn: full IAM role ARN.
##   - ManagedPolicyArn / PermissionsBoundaryArn: resolved from inputs.
##   - SamlProviderArn: federated principal used in the trust.
## Note: Useful for cross-stack wiring and CI assertions.

Outputs:

  ## Logical role name (CloudFormation ref), not the human string name.
  RoleName:
    Description: "IAM role name"
    Value: !Ref NetworkAdministratorRole

  ## Full IAM Role ARN.
  RoleArn:
    Description: "IAM role ARN"
    Value: !GetAtt NetworkAdministratorRole.Arn

  ## Resolved ARN for the attached managed policy.
  ManagedPolicyArn:
    Description: "Attached Network Administrator managed policy ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}${ManagedPolicyName}"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  InfrastructurePolicyArn:
    Description: "Infrastructure managed policy's ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--infrastructure"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  UtilitiesSupportPolicyArn:
    Description: "Utilities & Support managed policy's ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--utilities-support"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  ObservabilityTelemetryPolicyArn:
    Description: "Observability & Telemetry managed policy's ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--observability-telemetry"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  SystemsManagementPolicyArn:
    Description: "Systems Management managed policy's ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--systems-management"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  NetworkingServicesPolicyArn:
    Description: "Networking Services managed policy's ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--networking-services"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  SecurityCompliancePolicyArn:
    Description: "Security & Compliance managed policy's ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--security-compliance"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  WorkflowOrchestrationPolicyArn:
    Description: "Workflow Orchestration managed policy's ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--workflow-orchestration"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  WorkflowDeploymentPolicyArn:
    Description: "Workflow Deployment managed policy's ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}network--workflow-deployment"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  ## Resolved ARN for the enforced permissions boundary.
  PermissionsBoundaryArn:
    Description: "Enforced permissions boundary ARN"
    Value:
      !Sub
        - "arn:aws:iam::${AccountNumber}:policy${PathPart}${PermissionsBoundaryPolicyName}"
        - { PathPart: !If [ PathIsRoot, "/", !Ref CustomPolicyPath ] }

  ## ARN of the SAML provider used in the trust (for validation/reference).
  SamlProviderArn:
    Description: "Federated SAML provider ARN used in the trust"
    Value: !Sub "arn:aws:iam::${AccountNumber}:saml-provider/${SamlProviderName}"
