AWSTemplateFormatVersion: "2010-09-09"
Description: "Common Allow Policy — Systems Management (SSM Sessions/RunCommand, Associations/MW, Documents, Parameters, Automation read/exec)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-allow--systems-management
    Description: "IAM managed policy name for Systems Management allows"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkAllowSystemsManagementPolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Allow baseline for Systems Management (SSM sessions/RunCommand, Associations & MW, Documents, Parameter Store, Automation)."

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 4 - Systems Management

          ## -------------------------------------------------------------------
          ## SSM: sessions/RunCommand (tag-gated), docs/params, minimal Automation
          ## -------------------------------------------------------------------
          - Sid: SsmCoreOps
            Effect: Allow
            Action:
              - ssm:Describe*             ## read instance/doc/compliance info
              - ssm:List*                 ## list docs/instances/commands
              - ssm:Get*                  ## get parameters/docs/outputs
              - ssm:StartSession          ## start Session Manager session
              - ssm:ResumeSession         ## resume session
              - ssm:TerminateSession      ## end session
              - ssm:SendCommand           ## RunCommand dispatch
              - ssm:CancelCommand         ## cancel command
              - ssm:GetCommandInvocation  ## fetch command output
            Resource: "*"
            Condition:
              StringEquals:
                ssm:resourceTag/NetworkManaged: "true"  ## only our instances
              StringLikeIfExists:
                ssm:DocumentName:
                  - AWS-RunShellScript       ## allow AWS basic shell
                  - AWS-RunPowerShellScript  ## allow AWS PowerShell
                  - network-*                ## allow our runbooks

          ## -------------------------------------------------------------------
          ## SSM — Associations & Maintenance Windows: full lifecycle (create/update/delete/register/describe)
          ## -------------------------------------------------------------------
          - Sid: SsmAssocAndMW
            Effect: Allow
            Action:
              - ssm:*Association          ## State Manager associations: create/update/delete/describe/list
              - ssm:*MaintenanceWindow*   ## Maintenance Windows: create/update/delete/register target/task; describe/list
            Resource: "*"

          ## -------------------------------------------------------------------
          ## SSM — Parameter Store: manage only your namespace (/network/...)
          ## -------------------------------------------------------------------
          - Sid: SsmParametersNetworkPath
            Effect: Allow
            Action:
              - ssm:*Parameter*  ## Put/Get/Delete/Label/Describe/List parameters & versions under /network/
            Resource: arn:aws:ssm:*:*:parameter/network/*

          ## -------------------------------------------------------------------
          ## SSM — Your runbooks (Documents): authoring/admin for network-* docs
          ## -------------------------------------------------------------------
          - Sid: SsmDocsNetwork
            Effect: Allow
            Action:
              - ssm:*Document*  ## CreateDocument/UpdateDocument/UpdateDocumentDefaultVersion/DeleteDocument (and related describe/list)
            Resource: arn:aws:ssm:*:*:document/network-*

          ## -------------------------------------------------------------------
          ## SSM — Global document read: fetch/inspect any SSM document
          ## -------------------------------------------------------------------
          - Sid: SsmDocsRead
            Effect: Allow
            Action:
              - ssm:GetDocument           ## retrieve document content (any scope)
              - ssm:DescribeDocument      ## read document metadata/default version
              - ssm:ListDocuments         ## enumerate documents
              - ssm:ListDocumentVersions  ## list versions of a document
            Resource: "*"

          ## -------------------------------------------------------------------
          ## SSM — Automation: start executions only for your runbooks; caller creds only
          ## -------------------------------------------------------------------
          - Sid: SsmAutomationStartNetworkDocsOnly
            Effect: Allow
            Action:
              - ssm:StartAutomationExecution        ## kick off Automation execution for allowed docs
            Resource:
              - arn:aws:ssm:*:*:document/network-*  ## only your network-* runbooks
            Condition:
              "Null":
                ssm:AutomationAssumeRole: "true"    ## require NO AutomationAssumeRole (runs with caller context)

          ## -------------------------------------------------------------------
          ## SSM — Automation results: read back executions/steps
          ## -------------------------------------------------------------------
          - Sid: SsmAutomationReadResults
            Effect: Allow
            Action:
              - ssm:GetAutomationExecution            ## fetch a specific execution
              - ssm:DescribeAutomationExecutions      ## list executions
              - ssm:DescribeAutomationStepExecutions  ## list steps within an execution
              - ssm:ListAutomationExecutions          ## alternate listing API
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  ## ---------------------------------------------------------------------------
  ## Resolved ARN of the Systems Management allow policy
  ## ---------------------------------------------------------------------------
  NetworkAllowSystemsManagementPolicyArn:
    Description: "ARN of the Systems Management allow IAM managed policy"
    Value: !Ref NetworkAllowSystemsManagementPolicy
