AWSTemplateFormatVersion: "2010-09-09"
Description: "Merged IAM Managed Policy — Workflow-Orchestration (deny first, then allow)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network--workflow-orchestration
    Description: "IAM managed policy name for Workflow-Orchestration"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  WorkflowOrchestrationPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 7 - Deny: Development — Source & Orchestration

          ## -------------------------------------------------------------------
          ## CodeCommit: prevent repo lifecycle admin; allow normal Git ops
          ## -------------------------------------------------------------------
          - Sid: DenyCodeCommitRepoLifecycleAdmin
            Effect: Deny
            Action:
              - codecommit:CreateRepository             ## block creating repos (must be via IaC/pipeline)
              - codecommit:DeleteRepository             ## block deleting repos (protect history)
              - codecommit:UpdateRepositoryName         ## block renaming repos (breaks remotes/automation)
              - codecommit:UpdateRepositoryDescription  ## block unmanaged description changes
              - codecommit:PutRepositoryTriggers        ## block adding/modifying triggers (exfil paths)
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodePipeline: prevent pipeline lifecycle/admin (definition edits via CFN only)
          ## -------------------------------------------------------------------
          - Sid: DenyCodePipelineLifecycleAdmin
            Effect: Deny
            Action:
              - codepipeline:CreatePipeline  ## block creating pipelines outside IaC
              - codepipeline:UpdatePipeline  ## block editing pipeline definitions manually
              - codepipeline:DeletePipeline  ## block deleting pipelines outside change control
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodePipeline: prevent stage transition toggles
          ## -------------------------------------------------------------------
          - Sid: DenyCodePipelineStageTransitionToggle
            Effect: Deny
            Action:
              - codepipeline:DisableStageTransition  ## block pausing stage transitions
              - codepipeline:EnableStageTransition   ## block resuming transitions outside governance
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodePipeline: prevent webhook administration
          ## -------------------------------------------------------------------
          - Sid: DenyCodePipelineWebhookAdmin
            Effect: Deny
            Action:
              - codepipeline:PutWebhook     ## block creating/updating webhooks
              - codepipeline:DeleteWebhook  ## block deleting governed webhooks
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodePipeline: prevent custom action/job worker APIs
          ## -------------------------------------------------------------------
          - Sid: DenyCodePipelineCustomActionJobs
            Effect: Deny
            Action:
              - codepipeline:CreateCustomActionType         ## block defining custom action types
              - codepipeline:DeleteCustomActionType         ## block deleting custom action types
              - codepipeline:PollForJobs                    ## block human principals polling for jobs
              - codepipeline:AcknowledgeJob                 ## block manual job acknowledgements
              - codepipeline:PutJobSuccessResult            ## block faking job success
              - codepipeline:PutJobFailureResult            ## block forcing job failure
              - codepipeline:AcknowledgeThirdPartyJob       ## block acknowledging 3rd-party jobs
              - codepipeline:GetThirdPartyJobDetails        ## block fetching details of 3rd-party jobs
              - codepipeline:PutThirdPartyJobSuccessResult  ## block faking 3rd-party job success
              - codepipeline:PutThirdPartyJobFailureResult  ## block forcing 3rd-party job failure
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 7 - Allow: Development — Source & Orchestration

          ## -------------------------------------------------------------------
          ## IaC: deploy with CloudFormation (create/update stacks & change sets)
          ## -------------------------------------------------------------------
          - Sid: CloudFormationDeploy
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:Describe*
              - cloudformation:Get*
              - cloudformation:List*
              - cloudformation:ValidateTemplate
              - cloudformation:DetectStackDrift
              - cloudformation:DetectStackResourceDrift
              - cloudformation:CancelUpdateStack
              - cloudformation:ContinueUpdateRollback
            Resource: "*"

          ## -------------------------------------------------------------------
          ## SCM: CodeCommit read/write (Git pull/push + basic PR ops)
          ## -------------------------------------------------------------------
          - Sid: CodeCommitReadWrite
            Effect: Allow
            Action:
              - codecommit:Get*
              - codecommit:List*
              - codecommit:GitPull
              - codecommit:GitPush
              - codecommit:CreatePullRequest
              - codecommit:UpdatePullRequest*
              - codecommit:MergePullRequestByFastForward
              - codecommit:MergePullRequestBySquash
              - codecommit:MergePullRequestByThreeWay
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CI/CD Orchestration: operate CodePipeline executions (no pipeline admin)
          ## -------------------------------------------------------------------
          - Sid: CodePipelineOperations
            Effect: Allow
            Action:
              - codepipeline:Get*
              - codepipeline:List*
              - codepipeline:StartPipelineExecution
              - codepipeline:StopPipelineExecution
              - codepipeline:RetryStageExecution
              - codepipeline:PutApprovalResult
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Messaging — SNS publish/read
          ## -------------------------------------------------------------------
          - Sid: SnsPublishAndRead
            Effect: Allow
            Action:
              - sns:Publish
              - sns:Get*
              - sns:List*
              - sns:ConfirmSubscription
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Messaging — SNS minimal writes (scoped to network-*)
          ## -------------------------------------------------------------------
          - Sid: SnsOpsMinimalWrites
            Effect: Allow
            Action:
              - sns:Subscribe
              - sns:Unsubscribe
            Resource:
              - arn:aws:sns:*:*:network-*
              - arn:aws:sns:*:*:network-*:*

          ## -------------------------------------------------------------------
          ## Messaging — SQS consume/read
          ## -------------------------------------------------------------------
          - Sid: SqsConsumeAndRead
            Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ListQueues
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Messaging — SQS minimal writes (scoped to network-*)
          ## -------------------------------------------------------------------
          - Sid: SqsOpsMinimalWrites
            Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:ChangeMessageVisibility
            Resource:
              - arn:aws:sqs:*:*:network-*

## -------------------------------------------------------------------------- ##

Outputs:

  ManagedPolicyArn:
    Description: "Workflow Orchestration managed policy's ARN"
    Value: !Ref WorkflowOrchestrationPolicy
