AWSTemplateFormatVersion: "2010-09-09"
Description: "Merged IAM Managed Policy — Security & Compliance (deny first, then allow)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network--security-compliance
    Description: "IAM managed policy name for Security & Compliance"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  SecurityCompliancePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 6 - Deny: Security & Compliance

          ## -------------------------------------------------------------------
          ## Access Analyzer lifecycle/admin blocked; read still allowed by default ceiling
          ## -------------------------------------------------------------------
          - Sid: DenyAccessAnalyzerAdministration
            Effect: Deny
            Action:
              - access-analyzer:ApplyArchiveRule   ## block suppressing findings via archive rules
              - access-analyzer:Create*            ## block creating analyzers and related resources
              - access-analyzer:CreateArchiveRule  ## block explicit creation of archive rules
              - access-analyzer:Delete*            ## block deleting analyzers and their configs
              - access-analyzer:DeleteArchiveRule  ## block explicit deletion of archive rules
              - access-analyzer:StartResourceScan  ## block ad-hoc scans (must be governed)
              - access-analyzer:TagResource        ## block adding tags to analyzers
              - access-analyzer:UntagResource      ## block removing tags from analyzers
              - access-analyzer:Update*            ## block updates to analyzers and archive rules
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Prevent disabling GuardDuty (detector/admin/config)
          ## -------------------------------------------------------------------
          - Sid: DenyGuardDutyDisable
            Effect: Deny
            Action:
              - guardduty:DeleteDetector                   ## prevent deletion of GuardDuty detector
              - guardduty:DisableOrganizationAdminAccount  ## prevent disabling GuardDuty delegated org admin
              - guardduty:UpdateDetector                   ## prevent weakening GuardDuty detector config
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Prevent disabling Inspector (service/admin)
          ## -------------------------------------------------------------------
          - Sid: DenyInspectorDisable
            Effect: Deny
            Action:
              - inspector2:Disable                       ## prevent disabling Amazon Inspector
              - inspector2:DisableDelegatedAdminAccount  ## prevent removing Inspector delegated admin
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Prevent disabling Security Hub (service/admin)
          ## -------------------------------------------------------------------
          - Sid: DenySecurityHubDisable
            Effect: Deny
            Action:
              - securityhub:DisableOrganizationAdminAccount  ## prevent disabling Security Hub delegated org admin
              - securityhub:DisableSecurityHub               ## prevent disabling Security Hub itself
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Macie disable/org admin blocked
          ## -------------------------------------------------------------------
          - Sid: DenyMacieDisableAndOrgAdmin
            Effect: Deny
            Action:
              - macie2:DisableMacie                     ## block disabling Amazon Macie in the account
              - macie2:DisableOrganizationAdminAccount  ## block removing/disabling Macie delegated org admin
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 6 - Allow: Security & Compliance

          ## -------------------------------------------------------------------
          ## IAM Access Analyzer: read + policy validation
          ## -------------------------------------------------------------------
          - Sid: AccessAnalyzerReadOnlyAndValidation
            Effect: Allow
            Action:
              - access-analyzer:Get*            ## read analyzers, findings, and generated policies
              - access-analyzer:List*           ## list analyzers/findings/policy generations
              - access-analyzer:ValidatePolicy  ## validate IAM/STS/resource policies for issues
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Security services: read-only (Hub/GuardDuty/Inspector)
          ## -------------------------------------------------------------------
          - Sid: SecurityServicesReadOnly
            Effect: Allow
            Action:
              - guardduty:Get*         ## read GuardDuty detectors/findings/config
              - guardduty:List*        ## list detectors/IPSets/ThreatIntelSets/findings
              - inspector2:Get*        ## read Inspector v2 findings/coverage
              - inspector2:List*       ## list scans/findings/coverage resources
              - securityhub:Describe*  ## describe products/members/insights/settings
              - securityhub:Get*       ## get findings/insights/standards/control states
              - securityhub:List*      ## list products/standards/controls/members
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Macie: read-only
          ## -------------------------------------------------------------------
          - Sid: MacieReadOnly
            Effect: Allow
            Action:
              - macie2:Describe*  ## describe Macie configuration/classification jobs
              - macie2:Get*       ## get findings/results/sample data
              - macie2:List*      ## list jobs/findings/classification resources
            Resource: "*"

          ## -------------------------------------------------------------------
          ## AWS Firewall Manager: read-only
          ## -------------------------------------------------------------------
          - Sid: FirewallManagerReadOnly
            Effect: Allow
            Action:
              - fms:Get*   ## read FMS policies/violations
              - fms:List*  ## list policies/member accounts/resources
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Security Lake: read-only
          ## -------------------------------------------------------------------
          - Sid: SecurityLakeReadOnly
            Effect: Allow
            Action:
              - securitylake:Get*   ## read lake configuration/subscriptions
              - securitylake:List*  ## list sources/subscribers/lakes
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Detective: read-only
          ## -------------------------------------------------------------------
          - Sid: DetectiveReadOnly
            Effect: Allow
            Action:
              - detective:Get*       ## get graph/relationships/investigation data
              - detective:List*      ## list graphs/members/invitations
              - detective:Describe*  ## describe graphs/resources/organization settings
            Resource: "*"

          ## -------------------------------------------------------------------
          ## AWS Audit Manager: read-only
          ## -------------------------------------------------------------------
          - Sid: AuditManagerReadOnly
            Effect: Allow
            Action:
              - auditmanager:Get*       ## get assessments/evidence/control sets
              - auditmanager:List*      ## list assessments/evidence/control sets
              - auditmanager:Describe*  ## describe frameworks/settings/metadata
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EventBridge & Scheduler: read-only visibility
          ## -------------------------------------------------------------------
          - Sid: EventsAndSchedulerReadOnly
            Effect: Allow
            Action:
              - events:Describe*    ## describe rules/targets/buses/pipes links
              - events:Get*         ## get rule/event bus/connection/policy details
              - events:List*        ## list rules/targets/buses/archives/replays
              - scheduler:Describe* ## describe schedules/schedule groups
              - scheduler:Get*      ## get schedule definitions and policies
              - scheduler:List*     ## list schedules and groups
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EventBridge Pipes: read-only visibility
          ## -------------------------------------------------------------------
          - Sid: EventBridgePipesReadOnly
            Effect: Allow
            Action:
              - pipes:DescribePipe         ## read pipe definition/configuration
              - pipes:ListPipes            ## enumerate pipes in the account/region
              - pipes:ListTagsForResource  ## read tags on a pipe resource
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  ManagedPolicyArn:
    Description: "Security & Compliance managed policy's ARN"
    Value: !Ref SecurityCompliancePolicy
