AWSTemplateFormatVersion: "2010-09-09"
Description: "Merged IAM Managed Policy — Utilities & Support (deny first, then allow)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network--utilities-support
    Description: "IAM managed policy name for Utilities & Support"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  UtilitiesSupportPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 2 - Deny: Utilities & Support

          ## -------------------------------------------------------------------
          ## Prevent CloudShell exfil/infil and credential injection
          ## -------------------------------------------------------------------
          - Sid: DenyCloudShellFileXferAndCredInject
            Effect: Deny
            Action:
              - cloudshell:GetFileDownloadUrls  ## Prevent file exfil
              - cloudshell:GetFileUploadUrls    ## Prevent file infil
              - cloudshell:PutCredentials       ## Prevent credential seeding
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Q / Q Business administration blocked
          ## -------------------------------------------------------------------
          - Sid: DenyAmazonQAdministration
            Effect: Deny
            Action:
              - q:Associate*             ## block data source / app / user associations in Amazon Q
              - q:Create*                ## prevent creation of new Amazon Q resources
              - q:Delete*                ## prevent deletion of Amazon Q resources
              - q:Disassociate*          ## block disassociation of linked resources in Amazon Q
              - q:Put*                   ## prevent configuration/state changes
              - q:TagResource            ## prevent tag additions
              - q:UntagResource          ## prevent tag removals
              - q:Update*                ## prevent updates to Q resources/config
              - qbusiness:Associate*     ## block associations in Q Business
              - qbusiness:Create*        ## prevent creation of Q Business resources
              - qbusiness:Delete*        ## prevent deletion of Q Business resources
              - qbusiness:Disassociate*  ## block disassociations in Q Business
              - qbusiness:Put*           ## prevent configuration/state changes in Q Business
              - qbusiness:TagResource    ## prevent tag additions on Q Business resources
              - qbusiness:UntagResource  ## prevent tag removals on Q Business resources
              - qbusiness:Update*        ## prevent updates to Q Business resources/config
            Resource: "*"

          ## -------------------------------------------------------------------
          ## No org-wide RAM toggles
          ## -------------------------------------------------------------------
          - Sid: DenyOrgWideRAMSharing
            Effect: Deny
            Action:
              - ram:DisableSharingWithAwsOrganization  ## prevent disabling org-wide RAM sharing
              - ram:EnableSharingWithAwsOrganization   ## prevent enabling org-wide RAM sharing without governance
            Resource: "*"

          ## -------------------------------------------------------------------
          ## No Resource Explorer/Groups admin or bulk tagging
          ## -------------------------------------------------------------------
          - Sid: DenyResourceExplorerAndTaggingAdministration
            Effect: Deny
            Action:
              - resource-explorer-2:AssociateDefaultView     ## prevent setting/changing default Explorer view
              - resource-explorer-2:Create*                  ## block creation of Explorer views/indexes
              - resource-explorer-2:Delete*                  ## prevent deletion of Explorer views/indexes
              - resource-explorer-2:DisassociateDefaultView  ## prevent removing default Explorer view
              - resource-explorer-2:TagResource              ## prevent tag additions on Explorer resources
              - resource-explorer-2:UntagResource            ## prevent tag removals on Explorer resources
              - resource-explorer-2:Update*                  ## prevent updates to Explorer views/index configs
              - resource-groups:Create*                      ## block creation of new resource groups
              - resource-groups:Delete*                      ## prevent deletion of resource groups
              - resource-groups:Tag*                         ## prevent tag additions on groups
              - resource-groups:Untag*                       ## prevent tag removals on groups
              - resource-groups:Update*                      ## block updates/mutations to resource groups
              - tag:TagResources                             ## block bulk tag additions via Tag Editor
              - tag:UntagResources                           ## block bulk tag removals via Tag Editor
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 2 - Allow: Utilities & Support

          ## -------------------------------------------------------------------
          ## CloudShell: full access (deny policy blocks exfil/infil/cred inject)
          ## -------------------------------------------------------------------
          - Sid: CloudShellFull
            Effect: Allow
            Action:
              - cloudshell:*  ## full CloudShell console features
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Q: console chat + Console-to-Code only (no admin)
          ## -------------------------------------------------------------------
          - Sid: AmazonQUseInConsole
            Effect: Allow
            Action:
              - q:GenerateCodeFromCommands  ## console-to-code generation
              - q:GetConversation           ## fetch conversation
              - q:ListConversations         ## list past conversations
              - q:SendMessage               ## send chat message
              - q:StartConversation         ## start chat in console
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Q Business — chat-only usage (no admin)
          ## -------------------------------------------------------------------
          - Sid: QBusinessChatUseOnly
            Effect: Allow
            Action:
              - qbusiness:Chat      ## interactive chat sessions (async/streaming capable)
              - qbusiness:ChatSync  ## synchronous chat API for request/response calls
            Resource: "*"

          ## -------------------------------------------------------------------
          ## RAM: share lifecycle admin (create/update/delete/associate)
          ## -------------------------------------------------------------------
          - Sid: RamNetworkSharesAdmin
            Effect: Allow
            Action:
              - ram:CreateResourceShare                  ## create a share
              - ram:UpdateResourceShare                  ## update share
              - ram:DeleteResourceShare                  ## delete share
              - ram:AssociateResourceShare               ## attach resources/principals
              - ram:DisassociateResourceShare            ## detach resources/principals
              - ram:AssociateResourceSharePermission     ## attach permission
              - ram:DisassociateResourceSharePermission  ## detach permission
              - ram:AcceptResourceShareInvitation        ## accept invite
              - ram:RejectResourceShareInvitation        ## reject invite
              - ram:Get*                                 ## read shares/permissions
              - ram:List*                                ## list shares/associations
              - ram:TagResource                          ## tag a share
              - ram:UntagResource                        ## untag a share
            Resource: "*"

          ## -------------------------------------------------------------------
          ## RAM: author custom permissions + promote policy-origin shares
          ## -------------------------------------------------------------------
          - Sid: RamPermissionAuthoring
            Effect: Allow
            Action:
              - ram:CreatePermission                       ## create custom permission
              - ram:CreatePermissionVersion                ## add new version
              - ram:SetDefaultPermissionVersion            ## switch default version
              - ram:UpdatePermission                       ## edit permission
              - ram:DeletePermission                       ## delete permission
              - ram:DeletePermissionVersion                ## delete version
              - ram:ReplacePermissionAssociations          ## bulk swap permission on shares
              - ram:ListPermissionAssociations             ## list where permission is used
              - ram:PromotePermissionCreatedFromPolicy     ## promote policy-created perm
              - ram:PromoteResourceShareCreatedFromPolicy  ## promote policy-origin share
              - ram:Get*                                   ## read permissions
              - ram:List*                                  ## list permissions
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Resource Explorer / Groups / Tag APIs: read-only discovery
          ## -------------------------------------------------------------------
          - Sid: DiscoveryAndTagReadOnly
            Effect: Allow
            Action:
              - resource-explorer-2:Search  ## run resource searches
              - resource-explorer-2:Get*    ## read views/index details
              - resource-explorer-2:List*   ## list views/resources
              - resource-groups:Get*        ## read resource groups
              - resource-groups:List*       ## list groups
              - tag:GetResources            ## find resources by tags
              - tag:GetTagValues            ## list tag values
              - tag:GetTagKeys              ## list tag keys
              - account:ListRegions         ## enumerate regions
              - organizations:List*         ## list org structure (read)
            Resource: "*"

          ## -------------------------------------------------------------------
          ## AWS Support: full case management
          ## -------------------------------------------------------------------
          - Sid: SupportFull
            Effect: Allow
            Action:
              - support:*  ## create/update/view cases
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  ManagedPolicyArn:
    Description: "Utilities & Support managed policy's ARN"
    Value: !Ref UtilitiesSupportPolicy
