AWSTemplateFormatVersion: "2010-09-09"
Description: "Common Allow Policy — Observability & Telemetry (Config, CloudTrail, CloudWatch, Logs, X-Ray, OAM, Health, Trusted Advisor)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-allow--observability-telemetry
    Description: "IAM managed policy name for Observability/Telemetry allows"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkAllowObservabilityTelemetryPolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Allow baseline for Observability & Telemetry services (Config, CloudTrail, CloudWatch, Logs, X-Ray, OAM, Health, Trusted Advisor)."

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 3 - Observability & Telemetry

          ## -------------------------------------------------------------------
          ## AWS Config: read-only (no rule/recorder changes)
          ## -------------------------------------------------------------------
          - Sid: ConfigReadOnly
            Effect: Allow
            Action:
              - config:BatchGet*   ## batch reads
              - config:Deliver*    ## read delivery info/snapshots
              - config:Describe*   ## describe recorder/rules
              - config:Get*        ## get config/history
              - config:List*       ## list resources/rules
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CloudTrail: read-only (config/status/events lookup)
          ## -------------------------------------------------------------------
          - Sid: CloudTrailReadOnly
            Effect: Allow
            Action:
              - cloudtrail:DescribeTrails       ## list trails and settings
              - cloudtrail:GetEventSelectors    ## read event selectors
              - cloudtrail:GetInsightSelectors  ## read insight selectors
              - cloudtrail:GetTrailStatus       ## read trail status
              - cloudtrail:List*                ## list trails/queries
              - cloudtrail:LookupEvents         ## search events
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CloudWatch Logs: read + query (no admin/policy changes)
          ## -------------------------------------------------------------------
          - Sid: LogsReadAndQuery
            Effect: Allow
            Action:
              - logs:Describe*        ## list log groups/streams
              - logs:Get*             ## get log events/export tasks
              - logs:FilterLogEvents  ## on-the-fly filter query
              - logs:StartQuery       ## start Insights query
              - logs:GetQueryResults  ## retrieve query results
              - logs:List*            ## list queries/log groups
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CloudWatch metrics/alarms: read-only
          ## -------------------------------------------------------------------
          - Sid: CloudWatchReadOnly
            Effect: Allow
            Action:
              - cloudwatch:Describe*  ## describe alarms/metrics
              - cloudwatch:Get*       ## get metrics/alarms data
              - cloudwatch:List*      ## list dashboards/alarms
            Resource: "*"

          ## -------------------------------------------------------------------
          ## X-Ray: read-only (traces, service map)
          ## -------------------------------------------------------------------
          - Sid: XRayReadOnly
            Effect: Allow
            Action:
              - xray:Get*       ## get traces/insights
              - xray:BatchGet*  ## batch trace gets
              - xray:List*      ## list groups/sampling rules
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Health Dashboard: read-only
          ## -------------------------------------------------------------------
          - Sid: HealthReadOnly
            Effect: Allow
            Action:
              - health:Describe*  ## read Health events/impact
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Trusted Advisor: read-only checks
          ## -------------------------------------------------------------------
          - Sid: TrustedAdvisorReadOnly
            Effect: Allow
            Action:
              - trustedadvisor:Describe*  ## describe TA checks
              - trustedadvisor:List*      ## list checks/results
            Resource: "*"

          ## -------------------------------------------------------------------
          ## OAM: link to existing sinks; read state (sink admin denied by boundary)
          ## -------------------------------------------------------------------
          - Sid: ObservabilityAccessManagerLinking
            Effect: Allow
            Action:
              - oam:CreateLink  ## create link to sink
              - oam:DeleteLink  ## delete link
              - oam:Get*        ## read OAM entities
              - oam:List*       ## list links/sinks
              - oam:UpdateLink  ## update link config
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  NetworkAllowObservabilityTelemetryPolicyArn:
    Description: "ARN of the Observability/Telemetry allow IAM managed policy"
    Value: !Ref NetworkAllowObservabilityTelemetryPolicy
