AWSTemplateFormatVersion: "2010-09-09"
Description: "Permissions boundary (deny-guardrail) for Network Administrator role"

Parameters:

  PermissionsBoundaryName:
    Type: String
    Default: network--administrator--boundary
    Description: "AWS IAM permissions boundary managed policy"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

  ApprovedSsmInstanceProfiles:
    Type: CommaDelimitedList
    Default: "arn:aws:iam::*:instance-profile/network-ec2-ssm-*,arn:aws:iam::*:instance-profile/network-eks-ssm-*,arn:aws:iam::*:instance-profile/network-batch-ssm-*"
    Description: "Approved SSM-enabled instance profile ARNs/patterns"

  # DnssecKmsKeyArns:
  #   Type: String
  #   Default: ""
  #   Description: "KMS key ARNs dedicated to Route53 DNSSEC (Administrator-admin scopes)"
  #   AllowedPattern: '^$|^arn:aws:kms:[a-z0-9-]+:[0-9]{12}:key/[A-Fa-f0-9-]+(,arn:aws:kms:[a-z0-9-]+:[0-9]{12}:key/[A-Fa-f0-9-]+)*$'

# Conditions:
#   HasDnssecKmsKeys: !Not [ !Equals [ !Ref DnssecKmsKeyArns, "" ] ]

Resources:

  NetworkAdministratorPermissionsBoundary:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref PermissionsBoundaryName
      Path: !Ref CustomPolicyPath

      # Description: "Deny-guardrail boundary: broad allow, targeted explicit denies aligned to your relaxed model"
      Description: "Permissions boundary for Network Administrator: ceiling Allow* + admin-only explicit denies"

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##

          ## -------------------------------------------------------------------
          ## Ceiling = Allow all, then carve back with explicit denies below
          ## -------------------------------------------------------------------
          - Sid: GuardrailAllowAll
            Effect: Allow
            Action: "*"    ## broad allow on all actions (forms the maximum ceiling)
            Resource: "*"  ## broad allow on all resources (explicit denies take precedence below)

## -------------------------------------------------------------------------- ##
## 1 — Core Infrastructure

          ## -------------------------------------------------------------------
          ## ACM safety rail (admin-only)
          ## -------------------------------------------------------------------
          - Sid: DenyAcmTamper
            Effect: Deny
            Action:
              - acm:DeleteCertificate         ## prevent destructive cert deletions in prod
              - acm:UpdateCertificateOptions  ## prevent toggling key-usage/renewal options
            Resource: "*"

          ## -------------------------------------------------------------------
          ## ACM Private CA administration off (admins don't manage CA lifecycle)
          ## -------------------------------------------------------------------
          - Sid: DenyAcmPcaAdministration
            Effect: Deny
            Action:
              - acm-pca:CreateCertificateAuthority              ## prevent creating private CAs
              - acm-pca:DeleteCertificateAuthority              ## prevent deleting CAs
              - acm-pca:UpdateCertificateAuthority              ## prevent state/attr changes
              - acm-pca:RestoreCertificateAuthority             ## prevent CA restore
              - acm-pca:PutPolicy                               ## prevent CA resource policies
              - acm-pca:TagCertificateAuthority                 ## prevent adding tags on CAs
              - acm-pca:UntagCertificateAuthority               ## prevent removing tags on CAs
              - acm-pca:CreatePermission                        ## prevent delegate issue perms
              - acm-pca:DeletePermission                        ## prevent revoke delegate perms
              - acm-pca:ImportCertificateAuthorityCertificate   ## prevent CA cert import/rotate
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 2 — Utilities & Support

          ## -------------------------------------------------------------------
          ## SNS topic deletion and policy/admin blocked
          ## -------------------------------------------------------------------
          - Sid: DenySnsDestructiveAndPolicyAdmin
            Effect: Deny
            Action:
              - sns:AddPermission       ## prevent granting new publish/subscribe permissions on topics
              - sns:DeleteTopic         ## prevent deletion of SNS topics
              - sns:RemovePermission    ## prevent removal of existing topic permissions
              - sns:SetTopicAttributes  ## prevent policy/KMS/delivery attribute changes
            Resource: "*"

          ## -------------------------------------------------------------------
          ## SQS queue deletion and policy/admin blocked
          ## -------------------------------------------------------------------
          - Sid: DenySqsDeleteAndPolicyAdmin
            Effect: Deny
            Action:
              - sqs:AddPermission       ## prevent granting new permissions on queues
              - sqs:DeleteQueue         ## prevent deletion of SQS queues
              - sqs:RemovePermission    ## prevent removal of existing queue permissions
              - sqs:SetQueueAttributes  ## prevent policy/KMS/visibility/retention attribute changes
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EventBridge / Scheduler admin blocked (no rules/targets/buses lifecycle)
          ## -------------------------------------------------------------------
          - Sid: DenyEventsAndSchedulerAdministration
            Effect: Deny
            Action:
              - events:CreateEventBus    ## prevent creating custom event buses that bypass governance
              - events:DeleteEventBus    ## prevent deleting event buses (loss of routes/audits)
              - events:DeleteRule        ## prevent removing rules that drive automations/alerts
              - events:PutPermission     ## prevent cross-account bus sharing/permissions changes
              - events:PutRule           ## prevent creating/updating rules (schedules/pattern patterns)
              - events:PutTargets        ## prevent attaching targets (invocation pathways)
              - events:RemovePermission  ## prevent removing existing bus permissions
              - events:RemoveTargets     ## prevent detaching targets (silent disablement)
              - events:TagResource       ## prevent tag additions on EventBridge resources
              - events:UntagResource     ## prevent tag removals on EventBridge resources
              - scheduler:Create*        ## prevent creation of Scheduler schedules/groups
              - scheduler:Delete*        ## prevent deletions of schedules/groups
              - scheduler:TagResource    ## prevent tag additions on Scheduler resources
              - scheduler:UntagResource  ## prevent tag removals on Scheduler resources
              - scheduler:Update*        ## prevent updates to schedules (timing, payload, target)
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 3 — Observability: (none)

## -------------------------------------------------------------------------- ##
## 4 — Systems Management

          ## -------------------------------------------------------------------
          ## Prevent swapping to an unapproved profile after launch (reuses parameter)
          ## -------------------------------------------------------------------
          - Sid: DenyAssociateOrReplaceUnapprovedInstanceProfile
            Effect: Deny
            Action:
              - ec2:AssociateIamInstanceProfile            ## prevent attaching a new instance profile to an existing instance unless approved
              - ec2:ReplaceIamInstanceProfileAssociation   ## prevent swapping an instance’s current profile unless approved
            Resource: "*"
            Condition:
              StringNotLike:
                ec2:InstanceProfile: !Ref ApprovedSsmInstanceProfiles  ## deny when target instance profile ARN/name does NOT match the allowlist patterns

          ## -------------------------------------------------------------------
          ## Prevent removing the instance profile (keeps SSM capability attached)
          ## -------------------------------------------------------------------
          - Sid: DenyDisassociateInstanceProfile
            Effect: Deny
            Action: ec2:DisassociateIamInstanceProfile
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 5 — Networking Services

          ## -------------------------------------------------------------------
          ## VPC Peering — fully disabled (create/accept/modify/delete)
          ## -------------------------------------------------------------------
          - Sid: DenyVpcPeeringAll
            Effect: Deny
            Action:
              - ec2:CreateVpcPeeringConnection         ## Requester creates a peering request (same or cross account/region). State = pending-acceptance.
              - ec2:AcceptVpcPeeringConnection         ## Accepter approves a pending request; connection becomes active.
              - ec2:RejectVpcPeeringConnection         ## Accepter rejects a pending request; prevents the peering from being established.
              - ec2:DeleteVpcPeeringConnection         ## Either side deletes an active/pending peering; tears down the link (routes then become ineffective).
              - ec2:ModifyVpcPeeringConnectionOptions  ## Toggle per-VPC options on the peering: DNS resolution across VPCs (AllowDnsResolutionFromRemoteVpc) and legacy ClassicLink egress flags.
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 6 — Security & Compliance

          ## -------------------------------------------------------------------
          ## Detective admin blocked
          ## -------------------------------------------------------------------
          - Sid: DenyDetectiveAdministration
            Effect: Deny
            Action:
              - detective:Create*                          ## prevent creation of graphs/members/invitations and related resources
              - detective:Delete*                          ## prevent deletion of graphs/members/invitations and data sources
              - detective:DisableOrganizationAdminAccount  ## prevent disabling the org delegated admin for Detective
              - detective:EnableOrganizationAdminAccount   ## prevent enabling org delegated admin without governance
              - detective:Start*                           ## prevent starting monitoring/data-source ingestion operations
              - detective:TagResource                      ## prevent tag additions on Detective resources (cost/ABAC tamper)
              - detective:UntagResource                    ## prevent tag removals on Detective resources
              - detective:Update*                          ## prevent updates to Detective configurations and packages
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Security Lake admin blocked
          ## -------------------------------------------------------------------
          - Sid: DenySecurityLakeAdministration
            Effect: Deny
            Action:
              - securitylake:Create*        ## prevent creating data lakes, sources, subscribers, custom sources, and views outside governance
              - securitylake:Delete*        ## prevent deleting data lakes/views/subscribers (would disrupt central log lake)
              - securitylake:Put*           ## prevent config/resource policy changes (e.g., PutDataLakeSettings, auto-enable, subscriber notifications)
              - securitylake:TagResource    ## prevent tag additions on Security Lake resources (cost/compliance/ABAC integrity)
              - securitylake:UntagResource  ## prevent tag removals on Security Lake resources
              - securitylake:Update*        ## prevent updates to lake, sources, and subscriber configurations
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Audit Manager admin blocked
          ## -------------------------------------------------------------------
          - Sid: DenyAuditManagerAdministration
            Effect: Deny
            Action:
              - auditmanager:Create*        ## prevent creating assessments/frameworks/controls/delegations outside governance
              - auditmanager:Delete*        ## prevent deleting assessments/evidence/frameworks/reports
              - auditmanager:Put*           ## prevent configuration/report-publish mutations via Put* APIs
              - auditmanager:TagResource    ## prevent tag additions on Audit Manager resources
              - auditmanager:UntagResource  ## prevent tag removals on Audit Manager resources
              - auditmanager:Update*        ## prevent updates to assessments/settings/frameworks/controls
            Resource: "*"

## -------------------------------------------------------------------------- ##
## 7 — Development — Source & Orchestration: (none)

## -------------------------------------------------------------------------- ##
## 8 — Development — Build & Deployment

          ## -------------------------------------------------------------------
          ## ECS lifecycle restricted (admin not needed by admin-read stance)
          ## -------------------------------------------------------------------
          - Sid: DenyEcsClusterServiceTaskLifecycle
            Effect: Deny
            Action:
              - ecs:CreateCluster             ## prevent creating new ECS clusters (non-provisioning admin stance)
              - ecs:CreateService             ## prevent creating ECS services
              - ecs:DeleteCluster             ## prevent deleting clusters
              - ecs:DeleteService             ## prevent deleting services
              - ecs:DeregisterTaskDefinition  ## preserve task-def versions; no deregistration
              - ecs:RegisterTaskDefinition    ## prevent publishing new task definitions
              - ecs:RunTask                   ## prevent ad-hoc one-off task runs
              - ecs:StartTask                 ## prevent manual starts (EC2 launch type)
              - ecs:StopTask                  ## prevent stopping running tasks outside change control
              - ecs:UpdateService             ## prevent updates (scaling, task-def/version changes)
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EKS destructive/upgrade operations blocked
          ## -------------------------------------------------------------------
          - Sid: DenyEksDestructiveOps
            Effect: Deny
            Action:
              - eks:Delete*                 ## prevent deletion of clusters/nodegroups/add-ons and other destructive ops
              - eks:UpdateClusterConfig     ## prevent changing cluster networking/logging/compute settings
              - eks:UpdateClusterVersion    ## prevent upgrading cluster control plane version
              - eks:UpdateNodegroupConfig   ## prevent nodegroup config changes (scaling, AMI/launch template opts)
              - eks:UpdateNodegroupVersion  ## prevent nodegroup version/AMI upgrades
            Resource: "*"

          ## -------------------------------------------------------------------
          ## ECR push/delete/policy admin blocked (read/pull remains via ceiling)
          ## -------------------------------------------------------------------
          - Sid: DenyEcrPushDeleteAndPolicyAdmin
            Effect: Deny
            Action:
              - ecr:BatchDeleteImage        ## prevent bulk image/tag deletions
              - ecr:CompleteLayerUpload     ## prevent finalizing image pushes
              - ecr:DeleteRepository        ## prevent deleting repositories
              - ecr:DeleteRepositoryPolicy  ## prevent repo policy removal
              - ecr:InitiateLayerUpload     ## prevent starting image layer uploads
              - ecr:PutImage                ## prevent publishing image manifests
              - ecr:SetRepositoryPolicy     ## prevent repo policy administration
              - ecr:UploadLayerPart         ## prevent uploading image layer parts
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  ## ---------------------------------------------------------------------------
  ## Resolved ARN of the permissions-boundary managed policy.
  ## ---------------------------------------------------------------------------
  NetworkAdministratorPermissionsBoundaryArn:
    Description: "ARN of the Network Administrator IAM permissions boundary managed policy"
    Value: !Ref NetworkAdministratorPermissionsBoundary
