AWSTemplateFormatVersion: "2010-09-09"
Description: "Common Allow Policy — Security & Compliance (Access Analyzer, Security Hub/GuardDuty/Inspector, Macie, FMS, Security Lake, Detective, Audit Manager, Events/Scheduler/Pipes — read-only)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-allow--security-compliance
    Description: "IAM managed policy name for Security & Compliance allows"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkAllowSecurityCompliancePolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Allow baseline for Security & Compliance services (Access Analyzer validation, Security Hub/GuardDuty/Inspector read, Macie read, FMS read, Security Lake read, Detective read, Audit Manager read, EventBridge/Scheduler/Pipes read)."

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 6 - Security & Compliance

          ## -------------------------------------------------------------------
          ## IAM Access Analyzer: read + policy validation
          ## -------------------------------------------------------------------
          - Sid: AccessAnalyzerReadOnlyAndValidation
            Effect: Allow
            Action:
              - access-analyzer:Get*            ## read analyzers, findings, and generated policies
              - access-analyzer:List*           ## list analyzers/findings/policy generations
              - access-analyzer:ValidatePolicy  ## validate IAM/STS/resource policies for issues
            Resource: "*"

          ## -------------------------------------------------------------------
          ## IAM Access Analyzer: policy validation + CloudTrail-based generation
          ## -------------------------------------------------------------------
          - Sid: AccessAnalyzerPolicyGeneration
            Effect: Allow
            Action:
              - access-analyzer:ValidatePolicy          ## static analysis of IAM/STS/resource policies
              - access-analyzer:StartPolicyGeneration   ## kick off policy generation from CloudTrail activity
              - access-analyzer:GetGeneratedPolicy      ## retrieve the generated least-privilege policy JSON
              - access-analyzer:CancelPolicyGeneration  ## stop an in-flight generation job (cleanup)
              - access-analyzer:ListPolicyGenerations   ## list previous generation jobs/status
            Resource: "*"                               ## AA is account-scoped; actions are control-plane

          ## -------------------------------------------------------------------
          ## Security services: read-only (Hub/GuardDuty/Inspector)
          ## -------------------------------------------------------------------
          - Sid: SecurityServicesReadOnly
            Effect: Allow
            Action:
              - guardduty:Get*         ## read GuardDuty detectors/findings/config
              - guardduty:List*        ## list detectors/IPSets/ThreatIntelSets/findings
              - inspector2:Get*        ## read Inspector v2 findings/coverage
              - inspector2:List*       ## list scans/findings/coverage resources
              - securityhub:Describe*  ## describe products/members/insights/settings
              - securityhub:Get*       ## get findings/insights/standards/control states
              - securityhub:List*      ## list products/standards/controls/members
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Macie: read-only
          ## -------------------------------------------------------------------
          - Sid: MacieReadOnly
            Effect: Allow
            Action:
              - macie2:Describe*  ## describe Macie configuration/classification jobs
              - macie2:Get*       ## get findings/results/sample data
              - macie2:List*      ## list jobs/findings/classification resources
            Resource: "*"

          ## -------------------------------------------------------------------
          ## AWS Firewall Manager: read-only
          ## -------------------------------------------------------------------
          - Sid: FirewallManagerReadOnly
            Effect: Allow
            Action:
              - fms:Get*   ## read FMS policies/violations
              - fms:List*  ## list policies/member accounts/resources
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Security Lake: read-only
          ## -------------------------------------------------------------------
          - Sid: SecurityLakeReadOnly
            Effect: Allow
            Action:
              - securitylake:Get*   ## read lake configuration/subscriptions
              - securitylake:List*  ## list sources/subscribers/lakes
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Detective: read-only
          ## -------------------------------------------------------------------
          - Sid: DetectiveReadOnly
            Effect: Allow
            Action:
              - detective:Get*       ## get graph/relationships/investigation data
              - detective:List*      ## list graphs/members/invitations
              - detective:Describe*  ## describe graphs/resources/organization settings
            Resource: "*"

          ## -------------------------------------------------------------------
          ## AWS Audit Manager: read-only
          ## -------------------------------------------------------------------
          - Sid: AuditManagerReadOnly
            Effect: Allow
            Action:
              - auditmanager:Get*       ## get assessments/evidence/control sets
              - auditmanager:List*      ## list assessments/evidence/control sets
              - auditmanager:Describe*  ## describe frameworks/settings/metadata
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EventBridge & Scheduler: read-only visibility
          ## -------------------------------------------------------------------
          - Sid: EventsAndSchedulerReadOnly
            Effect: Allow
            Action:
              - events:Describe*    ## describe rules/targets/buses/pipes links
              - events:Get*         ## get rule/event bus/connection/policy details
              - events:List*        ## list rules/targets/buses/archives/replays
              - scheduler:Describe* ## describe schedules/schedule groups
              - scheduler:Get*      ## get schedule definitions and policies
              - scheduler:List*     ## list schedules and groups
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EventBridge Pipes: read-only visibility
          ## -------------------------------------------------------------------
          - Sid: EventBridgePipesReadOnly
            Effect: Allow
            Action:
              - pipes:DescribePipe         ## read pipe definition/configuration
              - pipes:ListPipes            ## enumerate pipes in the account/region
              - pipes:ListTagsForResource  ## read tags on a pipe resource
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  NetworkAllowSecurityCompliancePolicyArn:
    Description: "ARN of the Security & Compliance allow IAM managed policy"
    Value: !Ref NetworkAllowSecurityCompliancePolicy
