AWSTemplateFormatVersion: "2010-09-09"
Description: "Permissions boundary (deny-guardrail) for Network Architecture role"

Parameters:

  PermissionsBoundaryName:
    Type: String
    Default: network--architecture--boundary
    Description: "AWS IAM permissions boundary managed policy"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

  # ApprovedSsmInstanceProfiles:
  #   Type: CommaDelimitedList
  #   Default: "arn:aws:iam::*:instance-profile/network-ec2-ssm-*,arn:aws:iam::*:instance-profile/network-eks-ssm-*,arn:aws:iam::*:instance-profile/network-batch-ssm-*"
  #   Description: "Approved SSM-enabled instance profile ARNs/patterns"

  # DnssecKmsKeyArns:
  #   Type: String
  #   Default: ""
  #   Description: "KMS key ARNs dedicated to Route53 DNSSEC (Architecture-admin scopes)"
  #   AllowedPattern: '^$|^arn:aws:kms:[a-z0-9-]+:[0-9]{12}:key/[A-Fa-f0-9-]+(,arn:aws:kms:[a-z0-9-]+:[0-9]{12}:key/[A-Fa-f0-9-]+)*$'

# Conditions:
#   HasDnssecKmsKeys: !Not [ !Equals [ !Ref DnssecKmsKeyArns, "" ] ]

Resources:

  NetworkArchitecturePermissionsBoundary:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref PermissionsBoundaryName
      Path: !Ref CustomPolicyPath
      Description: "Deny-guardrail boundary: broad allow, targeted explicit denies aligned to your relaxed model"

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##

          ## -------------------------------------------------------------------
          ## Ceiling = Allow all, then carve back with explicit denies below
          ## -------------------------------------------------------------------
          - Sid: GuardrailAllowAll
            Effect: Allow
            Action: "*"    ## broad allow on all actions (forms the maximum ceiling)
            Resource: "*"  ## broad allow on all resources (explicit denies take precedence below)

## -------------------------------------------------------------------------- ##

Outputs:

  ## ---------------------------------------------------------------------------
  ## Resolved ARN of the permissions-boundary managed policy.
  ## ---------------------------------------------------------------------------
  NetworkArchitecturePermissionsBoundaryArn:
    Description: "ARN of the Network Architecture IAM permissions boundary managed policy"
    Value: !Ref NetworkArchitecturePermissionsBoundary
