AWSTemplateFormatVersion: "2010-09-09"
Description: "Common Allow Policy — Infrastructure (IAM PassRole to CFN exec roles, IAM discovery/SLR, KMS read/use, S3 network-* admin & object CRUD)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-allow--infrastructure
    Description: "IAM managed policy name for Infrastructure allows"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkAllowInfrastructurePolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Allow baseline for Infrastructure services (IAM PassRole→CFN exec roles, IAM discovery/SLR, KMS read/use, S3 network-* admin & object CRUD)."

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 1 - Infrastructure

          ## -------------------------------------------------------------------
          ## IAM: discovery + service-linked role creation (writes limited)
          ## -------------------------------------------------------------------
          - Sid: IdentityDiscoveryAndSLR
            Effect: Allow
            Action:
              - iam:CreateServiceLinkedRole  ## create SLRs when needed
              - iam:Get*                     ## read IAM entities/policies
              - iam:List*                    ## list IAM entities
            Resource: "*"

          ## -------------------------------------------------------------------
          ## IAM: policy simulation (Policy Simulator / CLI)
          ## -------------------------------------------------------------------
          - Sid: IamPolicySimulation
            Effect: Allow
            Action:
              - iam:SimulateCustomPolicy     ## run simulator against an inline/JSON policy document
              - iam:SimulatePrincipalPolicy  ## run simulator against a principal’s effective policy set
            Resource: "*"                    ## simulator needs wildcard; results are read-only

          ## -------------------------------------------------------------------
          ## KMS: read + cryptographic use (Encrypt/Decrypt/DataKey); boundary enforces ViaService constraints
          ## -------------------------------------------------------------------
          - Sid: KmsReadAndUse
            Effect: Allow
            Action:
              - kms:Decrypt                          ## decrypt (service-bound via boundary)
              - kms:DescribeKey                      ## read key metadata
              - kms:Encrypt                          ## encrypt (service-bound via boundary)
              - kms:GenerateDataKey                  ## data key generation (service-bound)
              - kms:GenerateDataKeyWithoutPlaintext  ## envelope key generation
              - kms:GetKeyPolicy                     ## read key policy
              - kms:List*                            ## list keys/aliases/grants
            Resource: "*"

          ## -------------------------------------------------------------------
          ## S3: allow listing all buckets (for discovery/selection in tools/CLI)
          ## -------------------------------------------------------------------
          - Sid: S3ListAllMyBuckets
            Effect: Allow
            Action:
              - s3:ListAllMyBuckets  ## list bucket names in the account
            Resource: "*"

          ## -------------------------------------------------------------------
          ## S3: admin on network-* buckets (no policy edits except via CFN)
          ## -------------------------------------------------------------------
          - Sid: S3NetworkBucketsAdminSafe
            Effect: Allow
            Action:
              - s3:CreateBucket                ## create network-* buckets
              - s3:PutPublicAccessBlock        ## enforce account-level PAB on bucket
              - s3:GetPublicAccessBlock        ## read PAB
              - s3:PutBucketOwnershipControls  ## set bucket owner preferred settings
              - s3:GetBucketOwnershipControls  ## read ownership controls
              - s3:PutBucketVersioning         ## enable versioning
              - s3:GetBucketVersioning         ## read versioning status
              - s3:PutBucketEncryption         ## set default SSE
              - s3:GetEncryptionConfiguration  ## read SSE config
              - s3:PutBucketTagging            ## tag buckets
              - s3:GetBucketTagging            ## read bucket tags
              - s3:GetBucketLocation           ## read region
              - s3:ListBucket                  ## list objects
              - s3:ListBucketVersions          ## list object versions
            Resource:
              - arn:aws:s3:::network-*

          ## -------------------------------------------------------------------
          ## S3: object CRUD in network-* (SSE required; multipart supported)
          ## -------------------------------------------------------------------
          - Sid: S3NetworkObjectsStrict
            Effect: Allow
            Action:
              - s3:PutObject                 ## upload object (single-part)
              - s3:GetObject                 ## download object
              - s3:GetObjectVersion          ## download specific version
              - s3:DeleteObject              ## delete object (current version)
              - s3:DeleteObjectVersion       ## delete a specific version
              - s3:AbortMultipartUpload      ## abort in-progress multipart upload
              - s3:CreateMultipartUpload     ## start multipart upload
              - s3:UploadPart                ## upload object part
              - s3:UploadPartCopy            ## copy part from another object
              - s3:CompleteMultipartUpload   ## finalize multipart upload
              - s3:ListMultipartUploadParts  ## list uploaded parts
            Resource:
              - arn:aws:s3:::network-*/*
            Condition:
              StringEqualsIfExists:
                s3:x-amz-acl: bucket-owner-full-control  ## ensure bucket owner owns objects
                s3:x-amz-server-side-encryption:
                  - AES256   ## allow SSE-S3
                  - aws:kms  ## allow SSE-KMS (see key allowlist below)
              StringLikeIfExists:
                s3:x-amz-server-side-encryption-aws-kms-key-id: arn:aws:kms:*:*:alias/network-*  ## only network-* KMS

## -------------------------------------------------------------------------- ##

Outputs:

  ## ---------------------------------------------------------------------------
  ## Resolved ARN of the Infrastructure allow policy
  ## ---------------------------------------------------------------------------
  NetworkAllowInfrastructurePolicyArn:
    Description: "ARN of the Infrastructure allow IAM managed policy"
    Value: !Ref NetworkAllowInfrastructurePolicy
