AWSTemplateFormatVersion: "2010-09-09"
Description: "Managed policy for Network Architecture (architecture-focused, read-mostly elsewhere)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-architecture-policy
    Description: "AWS IAM managed policy (role naming conventions live on the role)"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkArchitectureManagedPolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Grants network architects capabilities to prototype AWS networking & integrations"

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

# ---------------------------------------------------------------------------- #

          ## -------------------------------------------------------------------
          ## ACM: prototyping ops (delete/import/options OK; no export/account cfg)
          ## -------------------------------------------------------------------
          - Sid: CertificateManagerPrototyping
            Effect: Allow
            Action:
              - acm:RequestCertificate           ## issue ACM-managed certs for tests
              - acm:ImportCertificate            ## bring test certs (no private key export path)
              - acm:DeleteCertificate            ## clean up test certs
              - acm:UpdateCertificateOptions     ## toggle key-usage/managed-renewal on test certs
              - acm:DescribeCertificate          ## read cert status/validation/state
              - acm:GetCertificate               ## fetch cert/public chain (no private key)
              - acm:ListCertificates             ## enumerate certs
              - acm:ListTagsForCertificate       ## read tags
              - acm:AddTagsToCertificate         ## add tags
              - acm:RemoveTagsFromCertificate    ## remove tags
              - acm:RenewCertificate             ## trigger managed renewal
              - acm:ResendValidationEmail        ## retry email validation when needed
            Resource: "*"

          ## -------------------------------------------------------------------
          ## CodeArtifact: ADMIN (publish/read/administer repos/domains)
          ## -------------------------------------------------------------------
          - Sid: CodeArtifactAdmin
            Effect: Allow
            Action:
              - codeartifact:*  ## full CodeArtifact admin: domains/repos create/update/delete; publish/read; policies; tokens
            Resource: "*"

          ## -------------------------------------------------------------------
          ## ECR: ADMIN (push/pull/repo admin)
          ## -------------------------------------------------------------------
          - Sid: EcrAdmin
            Effect: Allow
            Action:
              - ecr:*  ## full ECR admin: repos create/delete; push/pull; policies; lifecycle/replication; scanning; tags
            Resource: "*"

          ## -------------------------------------------------------------------
          ## ECS: ADMIN (cluster/service/task lifecycle)
          ## -------------------------------------------------------------------
          - Sid: EcsAdmin
            Effect: Allow
            Action:
              - ecs:*  ## full ECS admin: clusters/services/task-defs/tasks/capacity-providers lifecycle; exec; reads/lists; tagging
            Resource: "*"

          ## -------------------------------------------------------------------
          ## EKS: ADMIN (cluster/nodegroup/addon lifecycle)
          ## -------------------------------------------------------------------
          - Sid: EksAdmin
            Effect: Allow
            Action:
              - eks:*  ## full EKS admin: clusters/nodegroups/addons/fargate-profiles lifecycle; access entries; idp config (not K8s RBAC)
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Service Discovery (read-only) & Service Catalog (provisioning allowed)
          ## -------------------------------------------------------------------
          - Sid: ServiceDiscoveryReadOnlyAndCatalogProvisioning
            Effect: Allow
            Action:
              - servicecatalog:Describe*                    ## describe resources
              - servicecatalog:Get*                         ## read products/portfolios
              - servicecatalog:List*                        ## list products/portfolios
              - servicecatalog:SearchProducts*              ## search catalog
              - servicediscovery:Get*                       ## read Cloud Map services/namespaces
              - servicediscovery:List*                      ## list services/instances
              - servicecatalog:ProvisionProduct
              - servicecatalog:TerminateProvisionedProduct
              - servicecatalog:UpdateProvisionedProduct
            Resource: "*"

# ---------------------------------------------------------------------------- #

Outputs:

  ## ---------------------------------------------------------------------------
  ## Resolved ARN of the NetworkArchitecture managed policy.
  ## ---------------------------------------------------------------------------
  ManagedPolicyArn:
    Description: "ARN of the NetworkArchitecture managed policy"
    Value: !Ref NetworkArchitectureManagedPolicy
