AWSTemplateFormatVersion: "2010-09-09"
Description: "Common Allow Policy — Utilities & Support (CloudShell full, Amazon Q chat, Q Business chat, RAM admin, Resource Explorer/Groups/Tag read, Support cases)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-allow--utilities-support
    Description: "IAM managed policy name for Utilities & Support allows"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkAllowUtilitiesSupportPolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Allow baseline for Utilities & Support services (CloudShell full, Amazon Q chat, Q Business chat, RAM admin & permission authoring, Resource Explorer/Groups/Tag read, AWS Support)."

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 2 - Utilities & Support

          ## -------------------------------------------------------------------
          ## CloudShell: full access (deny policy blocks exfil/infil/cred inject)
          ## -------------------------------------------------------------------
          - Sid: CloudShellFull
            Effect: Allow
            Action:
              - cloudshell:*  ## full CloudShell console features
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Q: console chat + Console-to-Code only (no admin)
          ## -------------------------------------------------------------------
          - Sid: AmazonQUseInConsole
            Effect: Allow
            Action:
              - q:GenerateCodeFromCommands  ## console-to-code generation
              - q:GetConversation           ## fetch conversation
              - q:ListConversations         ## list past conversations
              - q:SendMessage               ## send chat message
              - q:StartConversation         ## start chat in console
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Amazon Q Business — chat-only usage (no admin)
          ## -------------------------------------------------------------------
          - Sid: QBusinessChatUseOnly
            Effect: Allow
            Action:
              - qbusiness:Chat      ## interactive chat sessions (async/streaming capable)
              - qbusiness:ChatSync  ## synchronous chat API for request/response calls
            Resource: "*"

          ## -------------------------------------------------------------------
          ## RAM: share lifecycle admin (create/update/delete/associate)
          ## -------------------------------------------------------------------
          - Sid: RamNetworkSharesAdmin
            Effect: Allow
            Action:
              - ram:CreateResourceShare                  ## create a share
              - ram:UpdateResourceShare                  ## update share
              - ram:DeleteResourceShare                  ## delete share
              - ram:AssociateResourceShare               ## attach resources/principals
              - ram:DisassociateResourceShare            ## detach resources/principals
              - ram:AssociateResourceSharePermission     ## attach permission
              - ram:DisassociateResourceSharePermission  ## detach permission
              - ram:AcceptResourceShareInvitation        ## accept invite
              - ram:RejectResourceShareInvitation        ## reject invite
              - ram:Get*                                 ## read shares/permissions
              - ram:List*                                ## list shares/associations
              - ram:TagResource                          ## tag a share
              - ram:UntagResource                        ## untag a share
            Resource: "*"

          ## -------------------------------------------------------------------
          ## RAM: author custom permissions + promote policy-origin shares
          ## -------------------------------------------------------------------
          - Sid: RamPermissionAuthoring
            Effect: Allow
            Action:
              - ram:CreatePermission                       ## create custom permission
              - ram:CreatePermissionVersion                ## add new version
              - ram:SetDefaultPermissionVersion            ## switch default version
              - ram:UpdatePermission                       ## edit permission
              - ram:DeletePermission                       ## delete permission
              - ram:DeletePermissionVersion                ## delete version
              - ram:ReplacePermissionAssociations          ## bulk swap permission on shares
              - ram:ListPermissionAssociations             ## list where permission is used
              - ram:PromotePermissionCreatedFromPolicy     ## promote policy-created perm
              - ram:PromoteResourceShareCreatedFromPolicy  ## promote policy-origin share
              - ram:Get*                                   ## read permissions
              - ram:List*                                  ## list permissions
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Resource Explorer / Groups / Tag APIs: read-only discovery
          ## -------------------------------------------------------------------
          - Sid: DiscoveryAndTagReadOnly
            Effect: Allow
            Action:
              - resource-explorer-2:Search  ## run resource searches
              - resource-explorer-2:Get*    ## read views/index details
              - resource-explorer-2:List*   ## list views/resources
              - resource-groups:Get*        ## read resource groups
              - resource-groups:List*       ## list groups
              - tag:GetResources            ## find resources by tags
              - tag:GetTagValues            ## list tag values
              - tag:GetTagKeys              ## list tag keys
              - account:ListRegions         ## enumerate regions
              - organizations:List*         ## list org structure (read)
            Resource: "*"

          ## -------------------------------------------------------------------
          ## AWS Support: full case management
          ## -------------------------------------------------------------------
          - Sid: SupportFull
            Effect: Allow
            Action:
              - support:*  ## create/update/view cases
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  ## ---------------------------------------------------------------------------
  ## Resolved ARN of the Utilities & Support allow policy
  ## ---------------------------------------------------------------------------
  NetworkAllowUtilitiesSupportPolicyArn:
    Description: "ARN of the Utilities & Support allow IAM managed policy"
    Value: !Ref NetworkAllowUtilitiesSupportPolicy
