AWSTemplateFormatVersion: "2010-09-09"
Description: "Common Deny Policy — Security & Compliance (Access Analyzer, GuardDuty, Inspector, Security Hub, Macie)"

Parameters:

  ManagedPolicyName:
    Type: String
    Default: network-deny--security-compliance
    Description: "IAM managed policy name for Security & Compliance deny guardrails"

  CustomPolicyPath:
    Type: String
    Default: "/managed/network/"
    AllowedPattern: "^/([A-Za-z0-9+=,.@_-]+/)*$"
    Description: "IAM path prefix for policies (use / to disable)"

Resources:

  NetworkDenySecurityCompliancePolicy:

    Type: AWS::IAM::ManagedPolicy
    Properties:

      ManagedPolicyName: !Ref ManagedPolicyName
      Path: !Ref CustomPolicyPath
      Description: "Deny guardrails for Security & Compliance services (Access Analyzer, GuardDuty, Inspector, Security Hub, Macie)"

      PolicyDocument:
        Version: "2012-10-17"
        Statement:

## -------------------------------------------------------------------------- ##
## 6 - Security & Compliance

          ## -------------------------------------------------------------------
          ## Access Analyzer lifecycle/admin blocked; read still allowed by default ceiling
          ## -------------------------------------------------------------------
          - Sid: DenyAccessAnalyzerAdministration
            Effect: Deny
            Action:
              - access-analyzer:ApplyArchiveRule   ## block suppressing findings via archive rules
              - access-analyzer:Create*            ## block creating analyzers and related resources
              - access-analyzer:CreateArchiveRule  ## block explicit creation of archive rules
              - access-analyzer:Delete*            ## block deleting analyzers and their configs
              - access-analyzer:DeleteArchiveRule  ## block explicit deletion of archive rules
              - access-analyzer:StartResourceScan  ## block ad-hoc scans (must be governed)
              - access-analyzer:TagResource        ## block adding tags to analyzers
              - access-analyzer:UntagResource      ## block removing tags from analyzers
              - access-analyzer:Update*            ## block updates to analyzers and archive rules
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Prevent disabling GuardDuty (detector/admin/config)
          ## -------------------------------------------------------------------
          - Sid: DenyGuardDutyDisable
            Effect: Deny
            Action:
              - guardduty:DeleteDetector                   ## prevent deletion of GuardDuty detector
              - guardduty:DisableOrganizationAdminAccount  ## prevent disabling GuardDuty delegated org admin
              - guardduty:UpdateDetector                   ## prevent weakening GuardDuty detector config
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Prevent disabling Inspector (service/admin)
          ## -------------------------------------------------------------------
          - Sid: DenyInspectorDisable
            Effect: Deny
            Action:
              - inspector2:Disable                       ## prevent disabling Amazon Inspector
              - inspector2:DisableDelegatedAdminAccount  ## prevent removing Inspector delegated admin
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Prevent disabling Security Hub (service/admin)
          ## -------------------------------------------------------------------
          - Sid: DenySecurityHubDisable
            Effect: Deny
            Action:
              - securityhub:DisableOrganizationAdminAccount  ## prevent disabling Security Hub delegated org admin
              - securityhub:DisableSecurityHub               ## prevent disabling Security Hub itself
            Resource: "*"

          ## -------------------------------------------------------------------
          ## Macie disable/org admin blocked
          ## -------------------------------------------------------------------
          - Sid: DenyMacieDisableAndOrgAdmin
            Effect: Deny
            Action:
              - macie2:DisableMacie                     ## block disabling Amazon Macie in the account
              - macie2:DisableOrganizationAdminAccount  ## block removing/disabling Macie delegated org admin
            Resource: "*"

## -------------------------------------------------------------------------- ##

Outputs:

  NetworkDenySecurityCompliancePolicyArn:
    Description: "ARN of the Security & Compliance deny IAM managed policy"
    Value: !Ref NetworkDenySecurityCompliancePolicy
